version: 2.1
jobs:
  # Build the Node project.
  build:
    docker:
      - image: circleci/node:current

    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}

            # Fallback to using the latest cache if no exact match is found.
            - npm-packages-

      - run:
          name: Install NPM Packages
          command: npm install

      - run:
          name: Run Linters
          command: npm run lint

      - save_cache:
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - ~/.cache/npm

      - run:
          name: Build Project
          command: npm run build

      # Save our workspace so we can access it from other containers.
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - dist
            - package.json
            - package-lock.json

  # Publish npm packages.
  publish:
    docker:
      - image: circleci/node:lts

    steps:
      # Attach preview workspace to the `publish` container.
      - attach_workspace:
          at: /home/circleci/project

      - run:
          name: Create .npmrc File
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

      - run:
          name: Pack Package
          command: npm pack

      - run:
          name: Publish Package
          command: npm publish

workflows:
  build:
    jobs:
      - build
      - approval_required:
          type: approval
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

      # Publish NPM package only when tag starts with `v`
      - publish:
          requires:
            - approval_required
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/

  # publish:
  #   jobs:
  #     - approval_required:
  #         type: approval
  #         filters:
  #           tags:
  #             only: /^v.*/
  #           branches:
  #             ignore: /.*/

  #     # Publish NPM package only when tag starts with `v`
  #     - publish:
  #         requires:
  #           - approval_required
  #         filters:
  #           tags:
  #             only: /^v.*/
  #           branches:
  #             ignore: /.*/
